version: '3.3'

services:

  registry:
    image: registry:2.7.1
    restart: always
    environment:
      # - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      # - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - REGISTRY_HTTP_SECRET=secretstring
      # - REGISTRY_AUTH=htpasswd
      # - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      # - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    volumes:
      - ./volumes/registry/data/:/var/lib/registry
    expose:
      - "5000"