version: '3.3'

services:

  gitlab:
    image: gitlab/gitlab-ce:11.9.6-ce.0 
    restart: always 
    volumes:
      - /etc/localtime:/etc/localtime
      - ./volumes/gitlab/config:/etc/gitlab
      - ./volumes/gitlab/logs:/var/log/gitlab
      - ./volumes/gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 8082:80